name: veg-restore
channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.7
  - pip
  - configparser
  # Core scientific python
  - numpy
  - matplotlib
  - plotly

  # Spatial packages
  - rasterio  
  - rasterstats
  - geopandas
  - rioxarray
  - contextily
  - folium
  - sentinelhub
  - earthengine-api
  
  # Machine learning
  - sktime

  # Jupyter Environment
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions